### ISSUE TITLE
大佬你好，为什么下载完了无法生成mdict

### ISSUE THREAD

**Issue by 3cr13** [xyqyear/create_mdict_from_mediawiki#1]
大佬你好。我在windows下一开始下载你的最新源码，装依赖库（一开始用的python2.7，发现这是python3写的又换成3.7，win下的编译好的leveldb似乎只有3.6的，又换成3.6），运行wiki_mdict_leveldb.py，发现抓取某mediawiki的条目有500多条，爬了1个多小时，爬取完以后发现无法生成mdict（命令行里显示done，貌似默认是更新模式？之前抓取的它不会再去抓取）。我又运行wiki_mdict.py，发现抓取条目好像多的的，分第一页第二页第三页，第一页是300条第二页是600多条，第三页是700多条，加起来是wiki_mdict_leveldb.py的三倍，但是抓取条目的数量读完后就报错，无法抓取，错误提示如下

Traceback (most recent call last):
  File "H:\create_mdict_from_mediawiki-master\wiki_mdict.py", line 783, in <module>
    page_handler.work()
  File "H:\create_mdict_from_mediawiki-master\wiki_mdict.py", line 570, in work
    for i in range(self.process, len(self.all_pages)):
TypeError: object of type 'NoneType' has no len()

使用release0.1.0没有报错，但是条目只抓取到300多条（同一个站点），更严重的问题是没有生成mdict文件，命令行里只看到done，有db文件和存放图片的文件夹

大佬能修复一下吗？

**Comment by xyqyear** [comment]
@3cr13 

1.使用SQLite那个已经弃用，最好使用leveldb那个

2.第一次使用要关闭更新模式 

3.生成的文件是Achievement.txt，然后用mdict官方的制作工具转换成mdx，因为mdx文件本身不开源，所以无法直接生成mdx

那个制作工具的话在[这里](https://www.mdict.cn/wp/?page_id=5227&lang=zh)下载

4.请问是否能把config.py贴上来。

**Comment by 3cr13** [comment]
``# -*- coding:utf-8 -*-

# 网站地址
#site = 'https://thwiki.cc'
# upload地址
#upload = 'upload.thwiki.cc'
# API地址
#api_address = 'https://thwiki.cc/api.php'

site = 'https://www.hmoegirl.com'
upload = 'img.moegirl.com'
api_address = 'https://www.hmoegirl.com/api.php'

#site = 'https://minecraft-zh.gamepedia.com'
#upload = 'd1u5p3l4wpay3k.cloudfront.net/minecraft_zh_gamepedia'
#api_address = 'https://minecraft-zh.gamepedia.com/api.php'
# 需要下载的namespaces
# default:
namespaces = ['0']
# thwiki
#namespaces = ['0',  # 主
#              '4',  # THBWiki
#              '200',  # 用户wiki
#              '202',  # 用户资料
#              '506',  # 附带文档
#              '508',  # 游戏对话
#              '512',  # 歌词对话
#              ]
# 是否下载图片
is_download_image = True
# 是否是更新模式
is_update_mode = False
# 是否使用代理
is_use_proxy = False
# 代理池服务器地址
proxy_pool = '192.168.10.125:23333'
# 下载图片质量，因为wiki图片很多，所以要压缩一下。
image_quality = 50
# 日志输出模式:0是普通，1是debug
debug_mode = 1
# Test_mode
test_mode = False

**Comment by xyqyear** [comment]
@3cr13 有生成Achievement.txt吗，如果有的话就用那个制作工具就行了。

**Comment by 3cr13** [comment]
有，问一下制作工具source选Achievement.txt，DATA是选contents文件夹吗？tagret要求的mdx文件是要自己另外下载还是新建一个空文件？

**Comment by xyqyear** [comment]
@3cr13 data选图片的文件夹,target是mdx的保存目录,如果用这个版本的制作工具制作出来的mdx不能用的话可以尝试用老版本的,我原来用4.0的制作工具制作出来的貌似有点问题

老版本的制作工具的话网上应该找得到很多,记得是二点几的是最稳定的.

**Comment by 3cr13** [comment]
谢谢大佬，之前上传的config.py upload地址我填的有问题，这个站点有点特殊，在chrome的开发工具的network里查看图片地址有的是 https://www.hmoegirl.com/images/thumb/ 这样存在本站上的，有一些是img.moegirl.org 上的图片（毕竟是它的子站）但是在命令行运行的过程中(获取了300多条了，完成了快一半了)似乎没有下载任何图片，config.py中关闭了测试模式并且下载图片为ture。这是因为upload地址的原因吗？使用release0.1.0能获取一些图片。好像不用填写upload。但是就像一开始说的抓取的条目是不够的。站点自身统计是615个页面，所以目前最新的版本抓取到575条应该是准的。图片的upload地址应该如何填写呢？我分别试过 www.hmoegirl.com ， www.hmoegirl.com/images/和img.moegirl.org 但都没有获取到图片，是抓取条目结束才开始抓图片吗？

**Comment by xyqyear** [comment]
@3cr13 啊啊啊,这确实是我没有考虑到的情况,没有想到还能用俩站来存图片的,这样的话就只能改代码了,要不我改了单独给你?

**Comment by xyqyear** [comment]
@3cr13 而且貌似这个mdict的图片功能有些许问题(或者说是我没理解透彻),貌似图片那边的代码得完全重写了

**Comment by xyqyear** [comment]
@3cr13 刚刚稍微改了以下代码,  改成可以不用设置upload, 然后尝试解决了一下mdict制作工具图片读取的问题, 已经在调试了,不出意外等会儿就能commit上来了

**Comment by xyqyear** [comment]
@3cr13 我把旧版的生成工具上传上来了,新版的有点问题,打开某些页面会崩溃 [#d6e6b53](https://github.com/xyqyear/create_mdict_from_mediawiki/commit/d6e6b535947a8716991076ff5d9b0e1288808d09)

**Comment by xyqyear** [comment]
@3cr13 没啥问题的话我就把这个issue关啦

**Comment by 3cr13** [comment]
关吧
