### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by Fanyhow** [xyqyear/create_mdict_from_mediawiki#2]
您好，想请教一下，得到了Achievemen.txt后应该如何排版，
能使用外部css来控制排版吗？。

**Comment by xyqyear** [comment]
把css文件命名为与mdx文件一样的名字，放在同一目录下，软件就能自动读取了

**Comment by Fanyhow** [comment]
> 把css文件命名为与mdx文件一样的名字，放在同一目录下，软件就能自动读取了

好的谢谢解答，

还有一个问题就是 感觉图片的抓取还有问题，没有把图片都抓完，
比如
![image](https://user-images.githubusercontent.com/22214038/54651630-b4f2e580-4aee-11e9-898b-22dad981950b.png)
![image](https://user-images.githubusercontent.com/22214038/54651657-c89e4c00-4aee-11e9-81c6-ebaf06e7b89e.png)

**Comment by xyqyear** [comment]
有可能是下载的时候请求失败了，重新打开那个程序跑一遍应该就行了，会跳过已经保存的图片的。如果还不行你就留个那个网页的url到这个issue，有时间了我看看啥情况。

**Comment by Fanyhow** [comment]
嗯嗯我又重新跑了一遍，问题就解决了。感谢！
